version: '3'

services:

  ghapi:
    image: alpine:latest
    container_name: ghapi
    privileged: true
    restart: always
    environment:
      WX_APPID: ${WX_APPID}
      WX_SECRET: ${WX_SECRET}
      WX_TOKEN: ${WX_TOKEN}
      WX_MEDIA_ID: ${WX_MEDIA_ID}
      WX_OPEN_ID: ${WX_OPEN_ID}
      WX_AUTHOR: ${WX_AUTHOR}
      AI_TOKEN: ${AI_TOKEN}
      DATA_SOURCE: ${DATA_SOURCE}
      HOST: ${HOST}
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - type: bind
        source: ./ghapi
        target: /go/src/ghapi
      - type: bind
        source: /usr/share/zoneinfo/PRC
        target: /usr/share/zoneinfo/PRC
    command: /go/src/ghapi
    ports:
      - "8089:8089"
    extra_hosts:
      - "host.docker.internal:host-gateway"