version: '3.3'
services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    container_name: mongodb
    environment:
      - MONGODB_ROOT_PASSWORD=123456
    volumes:
      - ./data:/bitnami/mongodb
    ports:
      - 27017:27017
    restart: always