GET localhost:8089/callback?signature=547946c083001eaa5d671f50135e126c50838d8c&echostr=6934722161390122494&timestamp=1677809100&nonce=566368049


###
POST localhost:8089/callback?signature=547946c083001eaa5d671f50135e126c50838d8c&echostr=6934722161390122494&timestamp=1677809100&nonce=566368049
Content-Type: application/xml

<xml>
    <FromUserName>111</FromUserName>
    <MsgType>text</MsgType>
    <Content>这本书反映了什么呢</Content>
</xml>

###
GET localhost:8089/getAnswer?uuid=6404c6c2fcbe3062c6e734d5


###
GET localhost:8089/addDraft?uuid=6404c6c2fcbe3062c6e734d5

###
POST https://api.weixin.qq.com/cgi-bin/draft/add?access_token=
     https://api.weixin.qq.com/cgi-bin/draft/add?access_token=66_Ucie7vpUWKC0VBW9vH0kIqctTEoInJP5eZigwJpti5Pvn8ut_GUwXaNqm4jfZvEYHg5LyM5dSXgl1CYpsw5zqB0e35h873Jvxvs2D7JYVmT3AET93tG5uAVGP6ITAUcADAYFZ

Content-Type: application/json

{
  "articles": [
    {
      "title": "测试",
      "author": "虾客君",
      "content": "CONTENT",
      "thumb_media_id": "XuccSFRXw-w0Ozj76oDa5xaYaZF9BFEqsXSLAYPAeIo3VOAPe8Oslq47RtLriSSJ",
      "need_open_comment": 0,
      "only_fans_can_comment": 0
    }
  ]
}

{
  "articles": [
    {
      "thumb_media_id": "",
      "author": "ChatGPT",
      "only_fans_can_comment": 0,
      "digest": "",
      "content_source_url": "",
      "need_open_comment": 1,
      "title": "总结一下百年孤独这本书吧ksfb0",
      "content": "《百年孤独》是哥伦比亚作家加西亚·马尔克斯创作的一部现代文学经典，全书以马格达莲娜家族的历史为主线，描绘了从建国前的独立斗争到社会发展不断变革的一百年中，这个家族所经历的茫茫人世间的种种变迁。\n\n在书中，马尔克斯巧妙地运用魔幻现实主义的手法，设置了一系列超自然的事件，如人们上天、降雨、火灾、飞翔、奇妙的变形以及无穷无尽的神秘景象等，这些奇妙的描写融入了这部小说所描绘的虚构世界之中，让读者不禁为之惊叹。\n\n同时，在书中还探讨了人性的善恶和爱情的力量。人物形象丰满，情节跌宕起伏，语言简明通俗，形式独特，寓意深刻，是一部不可多得的文学巨作。"
    }
  ]
}

###
POST https://api.weixin.qq.com/cgi-bin/material/batchget_material?access_token=66_53ttPLhHkRLy_-bxQEuIeVG-F5pYJysrfeyQ1g3haZtmQvjM3iWI2KXjDhwDPaHL7JgFMZYtmBzElA3F_Y1XO0iWs5AU5TtpM9n78AJdEFhDeXNKzIdNvX_aLRkUQZhACABXG
Content-Type: application/json

{
  "type": "image",
  "offset": 0,
  "count": 20
}

###
GET  localhost:8089/addDraft?uuid=64049c4e6332a8fe02aed8d0
