GET localhost:8089/callback?signature=547946c083001eaa5d671f50135e126c50838d8c&echostr=6934722161390122494&timestamp=1677809100&nonce=566368049


###
POST localhost:8089/callback?signature=547946c083001eaa5d671f50135e126c50838d8c&echostr=6934722161390122494&timestamp=1677809100&nonce=566368049
Content-Type: application/xml

<xml>
    <FromUserName>111</FromUserName>
    <MsgType>text</MsgType>
    <Content>这本书反映了什么呢</Content>
</xml>

###
GET localhost:8089/getAnswer?uuid=6401bf0849f7f157900d8c19


###
GET localhost:8089/addDraft?uuid=6401bf0849f7f157900d8c19

###
POST https://api.weixin.qq.com/cgi-bin/draft/add?access_token=
Content-Type: application/json

{
  "articles": [
    {
      "title": "测试",
      "author": "虾客君",
      "content": "CONTENT",
      "thumb_media_id": "XuccSFRXw-w0Ozj76oDa5xaYaZF9BFEqsXSLAYPAeIo3VOAPe8Oslq47RtLriSSJ",
      "need_open_comment": 0,
      "only_fans_can_comment": 0
    }
  ]
}

###
POST https://api.weixin.qq.com/cgi-bin/material/batchget_material?access_token=
Content-Type: application/json

{
  "type": "image",
  "offset": 0,
  "count": 20
}